#include <stdlib.h>
#include <stdint.h>
#include "cmsis_boot/stm32f10x.h"
#include "cmsis_boot/system_stm32f10x.h"
#include "cmsis/core_cm3.h"
#include "stm_lib/inc/stm32f10x_rcc.h"
#include "stm_lib/inc/stm32f10x_gpio.h"
#include "stm_lib/inc/stm32f10x_tim.h"
#include "stm_lib/inc/stm32f10x_adc.h"
#include "stm_lib/inc/misc.h"
